import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';

class AddMedicationView extends StatefulWidget {
  const AddMedicationView({super.key});

    @override
      State<AddMedicationView> createState() => _AddMedicationViewState();
      }

      class _AddMedicationViewState extends State<AddMedicationView> {
        final _formKey = GlobalKey<FormState>();
          final _nameController = TextEditingController();
            final _dosageController = TextEditingController();
              TimeOfDay _selectedTime = const TimeOfDay(hour: 08, minute: 00);
                String _selectedFrequency = 'Her Gün'; // Türkçe varsayılan değer

                  @override
                    void dispose() {
                        _nameController.dispose();
                            _dosageController.dispose();
                                super.dispose();
                                  }

                                    Future<void> _selectTime(BuildContext context) async {
                                        final TimeOfDay? picked = await showTimePicker(
                                              context: context,
                                                    initialTime: _selectedTime,
                                                          builder: (BuildContext context, Widget? child) {
                                                                  return Theme(
                                                                            data: ThemeData.dark().copyWith(
                                                                                        colorScheme: const ColorScheme.dark(
                                                                                                      primary: Colors.white,
                                                                                                                    onPrimary: Colors.black,
                                                                                                                                  surface: Color(0xFF18181B),
                                                                                                                                                onSurface: Colors.white,
                                                                                                                                                            ),
                                                                                                                                                                        dialogBackgroundColor: const Color(0xFF09090B),
                                                                                                                                                                                  ),
                                                                                                                                                                                            child: child!,
                                                                                                                                                                                                    );
                                                                                                                                                                                                          },
                                                                                                                                                                                                              );
                                                                                                                                                                                                                  if (picked != null && picked != _selectedTime) {
                                                                                                                                                                                                                        setState(() {
                                                                                                                                                                                                                                _selectedTime = picked;
                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                              void _saveMedication() {
                                                                                                                                                                                                                                                  if (_nameController.text.trim().isEmpty || _dosageController.text.trim().isEmpty) {
                                                                                                                                                                                                                                                        ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                                                                                                                SnackBar(
                                                                                                                                                                                                                                                                          backgroundColor: Colors.redAccent,
                                                                                                                                                                                                                                                                                    content: Text(
                                                                                                                                                                                                                                                                                                'validation_error_message'.tr(),
                                                                                                                                                                                                                                                                                                            style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                  final String formattedTime = '${_selectedTime.hour.toString().padLeft(2, '0')}:${_selectedTime.minute.toString().padLeft(2, '0')}';

                                                                                                                                                                                                                                                                                                                                                      Navigator.pop(context, {
                                                                                                                                                                                                                                                                                                                                                            'name': _nameController.text.trim(),
                                                                                                                                                                                                                                                                                                                                                                  'dosage': _dosageController.text.trim(),
                                                                                                                                                                                                                                                                                                                                                                        'time': formattedTime,
                                                                                                                                                                                                                                                                                                                                                                              'frequency': _selectedFrequency,
                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                      @override
                                                                                                                                                                                                                                                                                                                                                                                        Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                            final bool isTr = context.locale.languageCode == 'tr';
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    final List<String> frequencies = isTr 
                                                                                                                                                                                                                                                                                                                                                                                                          ? ['Her Gün', 'Günde 2 Defa', 'Haftada Bir', 'İhtiyaç Halinde']
                                                                                                                                                                                                                                                                                                                                                                                                                : ['Every Day', 'Twice a Day', 'Once a Week', 'As Needed'];

                                                                                                                                                                                                                                                                                                                                                                                                                    if (!frequencies.contains(_selectedFrequency)) {
                                                                                                                                                                                                                                                                                                                                                                                                                          _selectedFrequency = frequencies[0];
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                  return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: const Color(0xFF09090B),
                                                                                                                                                                                                                                                                                                                                                                                                                                              appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: const Color(0xFF18181B),
                                                                                                                                                                                                                                                                                                                                                                                                                                                              elevation: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      leading: IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icon: const Icon(Icons.arrow_back, color: Colors.white),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () => Navigator.pop(context),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'add_screen_title'.tr(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style: const TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: FontWeight.w900,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  letterSpacing: 2.0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: SafeArea(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Form(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key: _formKey,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: ListView(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: const EdgeInsets.all(24.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'form_section_title'.tr().toUpperCase(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: Colors.zinc.shade500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 24),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'label_name'.tr(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style: const TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: Color(0xFFD4D4D8), // zinc-300
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 1.0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const SizedBox(height: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    controller: _nameController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hintText: 'hint_name'.tr(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hintStyle: TextStyle(color: Colors.zinc.shade600, fontSize: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        filled: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fillColor: const Color(0xFF18181B),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderSide: const BorderSide(color: Color(0xFF27272A)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            enabledBorder: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.